### PR TITLE
Tpm shell master merge

### PR DESCRIPTION
**Pull request by williamcroberts**

### CODE REVIEW

**Comment by williamcroberts** [comment]
@idesai --curently broken...

**Comment by williamcroberts** [comment]
@idesai this seems working now. I had to edit up tpm2_createpolicy, so you may wish to check it.

**Review by idesai — APPROVED** [review]
Checked, looks good. Also tested on my platform.

**Comment by idesai** [comment]
Will the current master fc15329 (has all the tools with policy support) be merged in this branch?

**Pull request merged**
